---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-java-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-java-app
  template:
    metadata:
      labels:
        app: my-java-app
    spec:
      terminationGracePeriodSeconds: 0
      containers:
      - name: java-api
        image: ttl.sh/my-java-app:503926e
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: my-java-app-service
spec:
  selector:
    app: my-java-app
  ports:
  - name: name-of-service-port
    protocol: TCP
    port: 8080
    targetPort: 8080